# Generated by Django 5.2.7 on 2025-11-12 17:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.FileField(upload_to='news_images/')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
