# Generated by Django 5.2.7 on 2025-11-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
