# Generated by Django 5.2.7 on 2025-11-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.TextField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=4)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='home.new')),
            ],
        ),
    ]
